<script setup>
import { ref, computed, onMounted } from "vue";
import Loader from "../components/Loader.vue";
import Card from "../components/Card.vue";

const searchText = ref("");
const loading = ref(false);
const allPosts = ref([]);
const title = ref("");

// get all posts from backend server and mongodb
const fetchPosts = async () => {
  try {
    loading.value = true;
    const response = await fetch("http://localhost:8000/api/v1/post", {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
      },
    });
    const result = await response.json();
    allPosts.value = result.data.reverse();
    if (result.data.length === 0) {
      title.value = "No Posts yet";
    }
  } catch (error) {
    alert(error);
  } finally {
    loading.value = false;
  }
};

// dynamic search filter
const filteredPosts = computed(() => {
  if (searchText.value === 0) {
    return allPosts.value;
  } else {
    const result = allPosts.value.filter(
      (item) =>
        item.name.toLowerCase().includes(searchText.value.toLowerCase()) ||
        item.prompt.toLowerCase().includes(searchText.value.toLowerCase())
    );
    if (result.length === 0) {
      title.value = "No Posts yet";
    }
    return result;
  }
});

onMounted(async () => {
  await fetchPosts();
});
</script>

<template>
  <section>
    <div class="home-title">
      <h1>The Community Showcase</h1>
      <p>
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>
    </div>
    <div class="search-input">
      <div class="input-wrapper">
        <div class="label-container">
          <label for="text">Search Posts</label>
        </div>
        <input
          type="text"
          id="text"
          name="text"
          placeholder="Search for an Image.."
          v-model="searchText"
          required
        />
      </div>
    </div>
    <div class="mt-10">
      <div class="flex justify-center items-center" v-if="loading">
        <Loader />
      </div>
      <div v-else>
        <h2 v-if="searchText">
          Showing Results for <span>{{ searchText }}</span>
        </h2>
        <div class="cards-wrapper">
          <template v-if="filteredPosts?.length > 0">
            <Card v-for="(post, i) in filteredPosts" :post="post" :key="i" />
          </template>
          <h2 v-else class="title">
            {{ title }}
          </h2>
        </div>
      </div>
    </div>
  </section>
</template>
