<script setup>
import { ref } from "vue";
import Loader from "../components/Loader.vue";

const searchText = ref("");
const loading = ref(false);
</script>

<template>
  <section>
    <div class="home-title">
      <h1>The Community Showcase</h1>
      <p>
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>
    </div>
    <div class="search-input">
      <div class="input-wrapper">
        <div class="label-container">
          <label for="text">Search Posts</label>
        </div>
        <input
          type="text"
          id="text"
          name="text"
          placeholder="Search for an Image.."
          v-model="searchText"
          required
        />
      </div>
    </div>
    <div class="mt-10">
      <div class="flex justify-center items-center" v-if="loading">
        <Loader />
      </div>
      <div v-else>
        <h2 v-if="searchText">
          Showing Results for <span>{{ searchText }}</span>
        </h2>
      </div>
    </div>
  </section>
</template>
