<script setup>
import { ref } from "vue";

const searchText = ref("");
</script>

<template>
  <section>
    <div class="home-title">
      <h1>The Community Showcase</h1>
      <p>
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>
    </div>
    <div class="search-input">
      <div class="input-wrapper">
        <div class="label-container">
          <label for="text">Search Posts</label>
        </div>
        <input
          type="text"
          id="text"
          name="text"
          placeholder="Search for an Image.."
          v-model="searchText"
          required
        />
      </div>
    </div>
  </section>
</template>
